import type { Note, Project } from "./types";
import { NOTE_COLORS } from "./types";

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const DEMO_PROJECTS: Project[] = [
  {
    id: "p_light",
    name: "Light exposure & sleep",
    color: NOTE_COLORS[0],
    summary: null,
    tags: ["circadian", "melatonin", "sample-size"],
    createdAt: now - 40 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: "p_pricing",
    name: "Pricing teardown",
    color: NOTE_COLORS[2],
    summary: null,
    tags: ["saas", "tiers"],
    createdAt: now - 30 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: "p_thesis",
    name: "Thesis: attention",
    color: NOTE_COLORS[1],
    summary: null,
    tags: ["attention", "deep-work"],
    createdAt: now - 20 * day,
    updatedAt: now - 3 * day,
  },
];

export const DEMO_NOTES: Note[] = [
  {
    id: "n_demo_1",
    pageKey: "https://nature.com/articles/light-and-sleep",
    url: "https://nature.com/articles/light-and-sleep",
    title: "Light and sleep",
    text: "Contradicts the 2019 paper: check sample size before citing the melatonin curve.",
    color: NOTE_COLORS[0],
    createdAt: now - 5 * day,
    updatedAt: now - 5 * day,
    projectId: "p_light",
    tags: ["melatonin", "methods"],
    archived: false,
    anchorText: "evening light delayed melatonin onset by 47 minutes",
  },
  {
    id: "n_demo_2",
    pageKey: "https://nature.com/articles/light-and-sleep",
    url: "https://nature.com/articles/light-and-sleep",
    title: "Light and sleep",
    text: "Use this chart in the intro section — blue light vs amber filters.",
    color: NOTE_COLORS[2],
    createdAt: now - 4 * day,
    updatedAt: now - 4 * day,
    projectId: "p_light",
    tags: ["chart"],
    archived: false,
  },
  {
    id: "n_demo_3",
    pageKey: "https://pubmed.ncbi.nlm.nih.gov/circadian",
    url: "https://pubmed.ncbi.nlm.nih.gov/circadian",
    title: "Circadian review",
    text: "Open question: does weekend catch-up sleep reverse weekday light debt?",
    color: NOTE_COLORS[3],
    createdAt: now - 3 * day,
    updatedAt: now - 3 * day,
    projectId: "p_light",
    tags: ["sleep-debt"],
    archived: false,
  },
  {
    id: "n_demo_4",
    pageKey: "https://stripe.com/pricing",
    url: "https://stripe.com/pricing",
    title: "Stripe pricing",
    text: "Usage-based tier sits between freemium and enterprise seat pricing.",
    color: NOTE_COLORS[2],
    createdAt: now - 8 * day,
    updatedAt: now - 8 * day,
    projectId: "p_pricing",
    tags: ["tiers"],
    archived: false,
  },
  {
    id: "n_demo_5",
    pageKey: "https://linear.app/pricing",
    url: "https://linear.app/pricing",
    title: "Linear pricing",
    text: "Flat per-seat with feature gates — compare against usage-based later.",
    color: NOTE_COLORS[4],
    createdAt: now - 7 * day,
    updatedAt: now - 6 * day,
    projectId: "p_pricing",
    tags: ["seats"],
    archived: false,
  },
  {
    id: "n_demo_6",
    pageKey: "https://calnewport.com/deep-work",
    url: "https://calnewport.com/deep-work",
    title: "Deep Work",
    text: "Attention residue after meetings may explain fragmented research days.",
    color: NOTE_COLORS[1],
    createdAt: now - 2 * day,
    updatedAt: now - 2 * day,
    projectId: "p_thesis",
    tags: ["attention"],
    archived: false,
  },
  {
    id: "n_demo_7",
    pageKey: "https://example.com/old-notes",
    url: "https://example.com/old-notes",
    title: "Archived scratch",
    text: "Old scratchpad — kept for reference only.",
    color: NOTE_COLORS[4],
    createdAt: now - 60 * day,
    updatedAt: now - 50 * day,
    projectId: null,
    tags: [],
    archived: true,
  },
];
